"""What we hold, and what we still need to read.

A source record is a citation. Holding the document is a different fact, and only
the second lets a claim be checked at page level. This separates them and ranks
the want list by how much of the corpus depends on each unread work.
"""

from datetime import datetime, timezone
from pathlib import Path

from .publications import current_registry, publication_keys


def _held_sources(conn):
    """source_id -> how the document was obtained."""
    held = {}
    for row in conn.execute(
        "SELECT source_id, url, sha256, mime_type, byte_length FROM captures "
        "WHERE source_id IS NOT NULL ORDER BY rowid"
    ):
        held.setdefault(row["source_id"], {
            "how": "deposit" if (row["url"] or "").startswith("local-deposit:") else "capture",
            "sha256": row["sha256"], "mime_type": row["mime_type"],
            "bytes": row["byte_length"],
        })
    return held


def acquisition_rows(conn):
    held = _held_sources(conn)
    keys = publication_keys(conn)
    registry = current_registry(conn)
    # How many objects depend on each source as their publication.
    objects_by_source = {}
    for key, entry in registry.items():
        if entry["resolution"] == "resolved" and entry["source_id"]:
            objects_by_source[entry["source_id"]] = (
                objects_by_source.get(entry["source_id"], 0) + keys.get(key, 0)
            )
    appearances = {row[0]: row[1] for row in conn.execute(
        "SELECT source_id, count(*) FROM appearances GROUP BY source_id")}
    claims = {row[0]: row[1] for row in conn.execute(
        "SELECT source_id, count(*) FROM claims GROUP BY source_id")}
    rows = []
    for row in conn.execute(
        "SELECT id,title,authors,issued_year,source_type,access_status,rights_status,notes "
        "FROM sources"
    ):
        source = dict(row)
        source["held"] = source["id"] in held
        source.update(held.get(source["id"], {}))
        source["published_objects"] = objects_by_source.get(source["id"], 0)
        source["appearances"] = appearances.get(source["id"], 0)
        source["claims"] = claims.get(source["id"], 0)
        # A work is worth chasing in proportion to how much rests on it unread.
        source["priority"] = (
            source["published_objects"] * 10 + source["appearances"] + source["claims"]
        )
        rows.append(source)
    return rows


def acquisition_metrics(conn):
    rows = acquisition_rows(conn)
    held = [r for r in rows if r["held"]]
    wanted = [r for r in rows if not r["held"] and r["priority"] > 0]
    return {
        "sources": len(rows),
        "sources_with_a_held_document": len(held),
        "sources_held_pct": len(held) / len(rows) if rows else 0,
        "sources_wanted_with_dependants": len(wanted),
        "objects_depending_on_an_unheld_publication": sum(r["published_objects"] for r in wanted),
    }


def write_acquisition_report(conn, destination):
    rows = acquisition_rows(conn)
    metrics = acquisition_metrics(conn)
    held = sorted((r for r in rows if r["held"]), key=lambda r: -r["priority"])
    wanted = sorted((r for r in rows if not r["held"] and r["priority"] > 0),
                    key=lambda r: -r["priority"])
    def label(r):
        who = (r["authors"] or "").split(";")[0].split(",")[0].strip() or "—"
        return "%s %s — %s" % (who, r["issued_year"] or "n.d.", (r["title"] or "")[:78])
    L = [
        "# Acquisition register",
        "",
        "> Generated by `ibi report-acquisitions`. What the project holds as a document, and what",
        "> it still needs to read. A source record is a citation; holding the document is a",
        "> separate fact, and only the second lets a claim be checked at page level.",
        "",
        "Generated: `%s`" % datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "",
        "| Measure | Current |",
        "|---|---:|",
        "| Source records | %d |" % metrics["sources"],
        "| With the document held | %d (%.1f%%) |" % (
            metrics["sources_with_a_held_document"], 100 * metrics["sources_held_pct"]),
        "| Wanted, with something depending on them | %d |" % metrics["sources_wanted_with_dependants"],
        "| Objects whose publication is unheld | %d |" % metrics["objects_depending_on_an_unheld_publication"],
        "",
        "Documents are archived privately by content hash under `data/private/archive/` and are",
        "never committed. What is committed is the hash, the citation and the locator.",
        "",
        "## Held",
        "",
        "| Work | How | Objects it publishes | Claims | SHA-256 |",
        "|---|---|---:|---:|---|",
    ]
    for r in held:
        L.append("| %s | %s | %d | %d | `%s` |" % (
            label(r).replace("|", "\\|"), r.get("how", "—"), r["published_objects"],
            r["claims"], (r.get("sha256") or "")[:12]))
    L += [
        "",
        "## Wanted",
        "",
        "Ranked by how much of the corpus rests on them unread: ten points per object the work",
        "publishes, one per appearance or claim already attributed to it.",
        "",
        "| Work | Objects it publishes | Appearances | Claims | Access |",
        "|---|---:|---:|---:|---|",
    ]
    for r in wanted[:40]:
        L.append("| %s | %d | %d | %d | %s |" % (
            label(r).replace("|", "\\|"), r["published_objects"], r["appearances"],
            r["claims"], r["access_status"]))
    if len(wanted) > 40:
        L.append("")
        L.append("Plus %d further sources with dependants. The full list is in the corpus." % (len(wanted) - 40))
    L += [
        "",
        "## How to add one",
        "",
        "Send the PDF. It is archived by content hash and linked to its source record:",
        "",
        "```sh",
        "ibi deposit <path> --source-id <SRC-…> --rights-status <status> --note '<provenance>'",
        "```",
        "",
        "`deposit` records a researcher-supplied file. It never implies a fetch, a robots check, or",
        "an access-control decision — use `capture` only for URLs the project may lawfully retrieve.",
        "",
    ]
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(L) + "\n", encoding="utf-8")
    return {"destination": str(destination), **metrics}
